const verifyWorkSpace = require('../common/verifyWorkSpace')
const clearLocalFolders = require('./clearLocalFolders')
const storyblokEnvTeardown = require('./storyblokEnvTeardown')
const createSbComponents = require('./createSbComponents')
const createSbFolders = require('./createSbFolders')
const genContactsWorkingData = require('./genContactsWorkingData')
const generateCertifications = require('./generateCertifications')
const generateCountries = require('./generateCountries')
const generateStaffs = require('./generateStaffs')
const generateCompanies = require('./generateCompanies')
const getCatalogWorkingData = require('./getCatalogWorkingData')
const generateCategories = require('./generateCategories')
const generateSeries = require('./generateSeries')
const generateProducts = require('./generateProducts')
const generateFeatures = require('./generateFeatures')
const generatePhotos = require('./generatePhotos')

module.exports = () => {
  return clearLocalFolders()
    .then(() => verifyWorkSpace())
    .then(() => storyblokEnvTeardown())
    .then(() => createSbComponents())
    .then(() => createSbFolders())
    .then(() => genContactsWorkingData())
    .then(() => generateCertifications())
    .then(() => generateCountries())
    .then(() => generateStaffs())
    .then(() => generateCompanies())
    .then(() => getCatalogWorkingData())
    .then(() => generateCategories())
    .then(() => generateSeries())
    .then(() => generateProducts())
    .then(() => generateFeatures())
    .then(() => generatePhotos())
    .catch(error => Promise.reject(error))
}
